### ISSUE TITLE
./scripts/ferm_sim.sh  error 

### ISSUE THREAD

**Issue by leeivan1007** [PhilipZRH/ferm#1]
when I run code

`./scripts/ferm_sim.sh `

appeared 

`CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling cublasSgemm`

![Screenshot from 2020-12-22 17-43-24](https://user-images.githubusercontent.com/14324351/102874432-6b7eb980-447d-11eb-8664-f56fa86ca8f3.png)

I try add the code, but it is not work
`torch.cuda.set_device(0)`

**Comment by PhilipZRH** [comment]
This seems to be a device/driver related issue. Could you try this?
`CUDA_VISIBLE_DEVICES=0 ./scripts/ferm_sim.sh`

**Comment by leeivan1007** [comment]
It has same problem.

There is my info of environment:
GPU:3080
Driver:455
Cuda:10.1

The other version of torch doesn't work too with 1.4.0 and 1.6.0

**Comment by PhilipZRH** [comment]
Closing the thread due to inactivity. Hope the new driver releases have solved the issue.
