### ISSUE TITLE
How to run the inference upon the existing model

### ISSUE THREAD

**Issue by MlLearnerAkash** [PhilipZRH/ferm#10]
Hii.. @albertzhan  and @PhilipZRH , thanks for your amazing work.

can you please provide a detailed instructions how to run your repository to establish your claimed results in the paper with the provided actor_*.pth and critic_*.pth file.

Thanking you,
Manna Akash

**Comment by PhilipZRH** [comment]
Hi Manna,

Thanks for your interest in this work. The checkpoints we provide in this repo are used to generate demonstrations, not the final pixel-based policies. We encourage you to read the README and play with the ferm_sim.sh script.

Best,
Ruihan

**Comment by MlLearnerAkash** [comment]
Thanks @PhilipZRH , will keep exploring on that.
Actually, me a new-bee to RL, so kind of you for your input
