### ISSUE TITLE
Questions about the real environment

### ISSUE THREAD

**Issue by bgyooPtr** [PhilipZRH/ferm#6]
There is no information about the actual environment in the repository, so I have a few questions.
How many steps per episode, and how many times are positive in the case of sparse reward?
Also, how many iterations of warmup sac?

**Comment by albertzhan** [comment]
If you are referring to 'actual' environment as the real world environment, then almost every parameter is the same as the included fetch suite, with the exception of the episode lengths being shortened to 30 steps. The amount of positive reward in each episode depends on the policy.
The contrastive pre training is done for 1600 iterations as indicated [here](https://github.com/PhilipZRH/ferm/blob/master/scripts/train_real_robot.sh).
