### ISSUE TITLE
How does this framework connect to a real robotic arm?

### ISSUE THREAD

**Issue by borninfreedom** [PhilipZRH/ferm#9]
It seems that the source code only contains the simulation code. How is the connection with the real manipulator, the acquisition and transmission of data, and the transmission of control instructions completed?

**Comment by albertzhan** [comment]
We created a gym wrapper (called RealRobotEnv-v0) around the [xarm7 sdk](https://github.com/xArm-Developer/xArm-Python-SDK). Everything is interacted through the gym interface of ```env.reset(), env.step()```.

**Comment by borninfreedom** [comment]
Why not open source this part?
